"""Reader for libRadtran OPAC optical-property netCDF files.

These files are generated by uvspec with ``write_optical_properties`` output.
Expected variables (per libRadtran output format):
    - ``output_dtauc``: optical depth per layer (nlyr,)
    - ``output_ssalb``: single-scattering albedo per layer (nlyr,)
    - ``output_pmom``: Legendre moments per layer (nlyr, nphamat, nmom+1)

Note: this module reads the *output* netCDF from libRadtran runs, not the
internal OPAC data tables (which are ASCII format).
"""

import netCDF4
import numpy as np


def read_opac_netcdf(path: str) -> dict:
    """Read OPAC optical properties from a libRadtran netCDF output file.

    Returns dict with:
        - ``wavelength_nm``: scalar or array (from file metadata if available)
        - ``dtauc``: optical depth per layer, shape (nlyr,)
        - ``ssalb``: single-scattering albedo, shape (nlyr,)
        - ``pmom``: Legendre moments, shape (nlyr, nmom+1)
        - ``altitude_km``: layer altitudes if available
    """
    with netCDF4.Dataset(path, "r") as ds:
        dtauc = ds.variables["output_dtauc"][:]
        ssalb = ds.variables["output_ssalb"][:]
        pmom = ds.variables["output_pmom"][:]

        # Squeeze phase-matrix dimension if singleton
        if pmom.ndim == 3 and pmom.shape[1] == 1:
            pmom = pmom[:, 0, :]

        result = {
            "dtauc": np.asarray(dtauc),
            "ssalb": np.asarray(ssalb),
            "pmom": np.asarray(pmom),
        }

        # Try to extract wavelength from global attributes
        if hasattr(ds, "wavelength"):
            result["wavelength_nm"] = float(ds.wavelength)
        elif hasattr(ds, "lambda"):
            result["wavelength_nm"] = float(getattr(ds, "lambda"))

        return result
