"""Regenerate ``canonical.yaml`` — the YAML twin of the ``canonical.py`` scene.

The emitted config describes the exact same experiment as
``canonical.build_scene(canonical.build_composite())`` (same SCENE_KW, same
three Mie blocks with od_inversion placements, same shared grids), except
that ``aerosol.output_dir`` is the RELATIVE path ``output``: the explicit
``.master``/``.LAYER`` files are written relative to the working directory
at run time (loading/validating a config writes nothing).

Run from this directory (any cwd works — ``canonical.py`` is found next to
this script):

    cd examples/multicomponent_viz && python make_yaml.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import canonical  # script directory is on sys.path when run as a script

from pyradtran.config import export_config

TARGET = Path(__file__).resolve().parent / "canonical.yaml"

HEADER = """\
# canonical.yaml — YAML twin of the canonical multicomponent_viz scene
# (SCENE_KW + three Mie blocks with od_inversion placements on shared grids).
#
# GENERATED by make_yaml.py from canonical.py — do not edit by hand;
# regenerate with:
#     cd examples/multicomponent_viz && python make_yaml.py
#
# `aerosol.output_dir: output` is RELATIVE: explicit .master/.LAYER files are
# written relative to the working directory at run time (loading and
# validating write no files). Either run from the example directory:
#     cd examples/multicomponent_viz && pyradtran run canonical.yaml
# or point the output/plot dirs elsewhere: set `aerosol.output_dir` in a copy
# of this file and pass `--plot-dir` to `pyradtran run`.
#
# config_version 1.
"""


def config_dict() -> dict:
    """Config equivalent to canonical.build_composite() + build_scene().

    Mirrors ``tests/test_config_roundtrip.py::_config_dict`` (same shape,
    same constants) but with the relative ``output_dir: output``; that test
    enforces the YAML/API equivalence, and this generator keeps the committed
    file in sync with canonical.py.
    """
    blocks = [
        {
            "kind": "mie",
            "name": b["name"],
            "refractive_index": {
                "wavelength_um": canonical._WL_RI,
                "n_real": b["n_real"],
                "k_imag": b["k_imag"],
            },
            "size_distribution": {
                "kind": "lognormal",
                "params": {"r_g_um": b["r_g_um"], "sigma_g": b["sigma_g"]},
            },
            "particle_density_kg_m3": b["density"],
            "placement": {
                "kind": "od_inversion",
                "tau_ref": b["tau_550"],
                "ref_nm": canonical.REF_NM,
                "scale_height_km": b["scale_height_km"],
            },
        }
        for b in canonical.BLOCKS
    ]
    return {
        "config_version": 1,
        "name": "multicomponent_viz_canonical",
        "scene": dict(canonical.SCENE_KW),
        "aerosol": {
            "wavelength_grid_um": canonical.WAVELENGTHS_UM,
            "altitude_grid_km": canonical.ALTITUDE_GRID_KM,
            "n_legendre": canonical.N_LEGENDRE,
            "output_dir": "output",
            "blocks": blocks,
        },
    }


def main() -> int:
    """Write canonical.yaml = comment header + canonical YAML config."""
    export_config(config_dict(), TARGET)  # pure YAML (no comments)
    body = TARGET.read_text(encoding="utf-8")
    TARGET.write_text(HEADER + body, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
