import os
import sys

sys.path.insert(0, os.path.abspath("../src"))

from importlib.metadata import version as get_version

project = "pyRadtran"
copyright = "2026, Fan Zhang"
author = "Fan Zhang"
release = get_version("pyradtran")

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "xarray": ("https://docs.xarray.dev/en/stable/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
}

# Nitpicky mode (-n) flags third-party and autogenerated type references that
# autodoc pulls from pydantic Field constraints and numpy type hints. These are
# not documentation defects; ignore them broadly by module/shape.
nitpick_ignore_regex = [
    (r"py:class", r"pydantic\..*"),
    (r"py:class", r"ConfigDict"),
    (r"py:class", r"_PydanticGeneralMetadata"),
    (r"py:class", r"annotated_types\..*"),
    (r"py:class", r"numpy\..*"),
    (r"py:class", r"xarray\..*"),
    (r"py:class", r"xr\..*"),
    (r"py:class", r"collections\.abc\..*"),
    (r"py:class", r"pathlib\.Path"),
    (r"py:class", r"\d+\.\d+"),  # numeric Field bounds rendered as class refs (0.0, 1000000.0, ...)
    (r"py:class", r"Dictionary"),
    # Bare-name cross-refs to pyradtran classes in src docstrings (would need full paths to resolve).
    (r"py:class", r"PlacedBlock|LayerOptics|RefractiveIndex|CompositeAerosol|SpeciesOptics"),
    (r"py:class", r"pyradtran\.optics\.mie\._SpeciesOptics"),
]

templates_path = ["_templates"]
# The Package Interface (automodule:: pyradtran) re-exports names that the
# per-module automodules also document; that overlap is inherent to exposing
# both surfaces and is not a defect, so silence the duplicate-object warnings.
suppress_warnings = ["duplicate.object"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
